### ISSUE TITLE
Google not working anymore

### ISSUE THREAD

**Issue by FabioManoel1977** [uyjulian/Translation-Aggregator#1]
sorry bad english

Google translation not working anymore, Show up the message "Failed to create connection."

All other translators is working nicely

I do believe that google translation machine changed the way that is connected

**Comment by uyjulian** [comment]
I plan on fixing that later.

**Comment by FabioManoel1977** [comment]
Thank you very much, and I am really very grateful for you to keep Translation-Aggregator project alive. Looks like no one cares besides you about it nowadays, then, in the day that you also abandon Translation-Aggregator everybody like me that loves hentai games and not understands Japanese will be doomed.

Thank you very much from the bottom of my heart.

**Comment by FabioManoel1977** [comment]
I find out that  Sinflower version is working fine, then I will use  Sinflower version from now on till you fix your version, thank you very much.
https://github.com/Sinflower/Translation-Aggregator/releases

**Comment by uyjulian** [comment]
The source code for mine and Sinflower's relating to the Google translator window is exactly the same, so I'm not sure what's going wrong. I'll have to look into it more.

**Comment by uyjulian** [comment]
Fixed
