### ISSUE TITLE
Donation option

### ISSUE THREAD

**Issue by henkieaardpeer** [uyjulian/Translation-Aggregator#13]
Sorry, this is not really an issue with the program, but can you perhaps consider adding a Paypal donation option to your Readme page? You might regard it just as a hobby but I like rewarding people who save my life by maintaining these programs really well

**Comment by uyjulian** [comment]
I have a Patreon: https://www.patreon.com/uyjulian

However, I don't really have an issue with money right now, so you don't need to send money to me. I'd rather you send money to the Internet Archive or the EFF.

**Comment by henkieaardpeer** [comment]
OK, understood
