### ISSUE TITLE
Google still not working

### ISSUE THREAD

**Issue by FabioManoel1977** [uyjulian/Translation-Aggregator#14]
Please, I beg you fix it. Not make my life sad. I want to play my hentai games.

original text:
「お兄ちゃん。はい、ビールもラスト１本」

show in google like this:

Unrecognized response received:

[[["[\"Onii-chan. Yes. Beer is also one last\"]","【「Onii-chan。。はい。。ビールもラスト１本」】",null,null,3,null,null,null,[[["7b78faa1329566192a016d05fd7850f4","ja_en_2018q4.md"]
]
]
]
,[null,null,null,"[`Onii - chan.. Hai.. Bīru mo rasuto 1-pon']"]
]
,null,"ja",null,null,null,null,null,[["ja"]
,null,[1.0]
,["ja"]
]
]

**Comment by uyjulian** [comment]
Are you using v1.0.2 from here: https://github.com/uyjulian/Translation-Aggregator/releases/download/v1.0.2/TranslationAggregator.v1.0.2.7z
