### ISSUE TITLE
Google Problem on V.1.0.2

### ISSUE THREAD

**Issue by TsumiHokiro** [uyjulian/Translation-Aggregator#15]
Google broke again. This time on 1.0.2. Been using it for a few days and it isn't a temporary thing it seems...

Text it spills:
Unrecognized response received:

[[["Item Equipment Changeover Status Skill Travel Record Save Road System 50G Training Center Gisele Lv2HP144 / 160AP96 / 100NEXT92","アイテム装備着替えステータススキル旅の記録セーブロードシステム50Ｇ訓練場ジゼルLv2HP144/160AP96/100NEXT92",null,null,3,null,null,null,[[["ad1cd15d6208d1d2821f97fa1c973637","ja_en_2019q2.md"]
]
]
]
,[null,null,null,"Aitemu sōbi kigae sutētasusukiru tabinokiroku sēburōdoshisutemu 50 G kunren-ba jizeru Lv 2 HP 144/ 160 AP 96/ 100 nekusuto 92"]
]
,null,"ja",null,null,null,null,null,[["ja"]
,null,[1.0]
,["ja"]
]
]

**Comment by henkieaardpeer** [comment]
Same here.

**Comment by uyjulian** [comment]
Fixed in v1.0.3
https://github.com/uyjulian/Translation-Aggregator/releases/tag/v1.0.3
