### ISSUE TITLE
Program closes when launching text kooker

### ISSUE THREAD

**Issue by ZLTM** [uyjulian/Translation-Aggregator#22]
Running win 10 with atlas 14
On a fresh install launch the text hooker, the program closes.
Tried running as a regular user, as an admin, and with win 8 compatibility.

Translating text by copy-pasting takes some time, maybe that's related to this issue?

**Comment by uyjulian** [comment]
What "text hooker" are you referencing?

**Comment by ZLTM** [comment]
The option present on the header button 'Tools'

**Comment by uyjulian** [comment]
It is not supported.

Use Textractor and enable automatic clipboard reading using the clipboard window on the ATLAS subwindow.

**Comment by ZLTM** [comment]
had to do some tinkering but now it's working with textractor and jparser, thanks!
