### ISSUE TITLE
None of my setting save 

### ISSUE THREAD

**Issue by CommicKick69ing** [uyjulian/Translation-Aggregator#23]
None of my setting save and I keep getting this error "unable to create socket. hooking engine wont work" Any help fixing this?

**Comment by uyjulian** [comment]
What features are you using

**Comment by CommicKick69ing** [comment]
im not using any feature i  just booting the app up and I get that message

**Comment by uyjulian** [comment]
Turn off all other antivirus and firewall except Windows Defender, Windows Firewall, and System Center Endpoint Protection.

**Comment by CommicKick69ing** [comment]
that doesnt work

**Comment by uyjulian** [comment]
Your network configuration appears to be broken.

Have you tried this on a fresh install of Windows 10?
