### ISSUE TITLE
Enhancement: Add button that copies JParser result to clipboard separated by spaces

### ISSUE THREAD

**Issue by botnet88** [uyjulian/Translation-Aggregator#28]
Would it be possible to get the parsed Japanese text into my clipboard separated by spaces?

What I mean by this is:

Original clipboard text:
雪国。
これから暮らすここを一言で表すならそれに尽きる。
「こっちだったよな……」
記憶とメモを頼りに向かうのはこれからの住処。
「お……」
案外それは早く見つかる。おかげでこれ以上寒さに凍えずに済みそうだ。

JParser output:
![jparser](https://user-images.githubusercontent.com/61393492/94332158-3b1ba200-ff98-11ea-9d26-4fc3e0fe7992.png)

What I want to have in my clipboard after the parsing is complete is:
雪国 。
これから 暮らす ここ を 一言 で 表す なら それに 尽きる 。
「 こっち だった よな ……」
記憶 と メモ を 頼り に 向かう の は これから の 住処 。
「 お ……」
案外 それは 早く 見つかる 。 おかげで これ以上 寒さ に 凍えず に 済み そうだ 。

**Comment by Frank54524** [comment]
I had problems with a game I've been playing recently as well I had to use
textractor because agth was constantly filled with bad repetitive text

**Comment by botnet88** [comment]
@Frank54524 
That's not related to my issue.

**Comment by uyjulian** [comment]
It would probably require a rewrite of the JParser output window since it is not an editable/selectable control.

**Comment by botnet88** [comment]
I was playing around with the Japanese Text Analysis Tool's JParser class, and was able to create a program that does what I want. It's a bit buggy, but for me it works well enough.

Find it here: https://github.com/botnet88/jparser-output
