### ISSUE TITLE
Systran not working

### ISSUE THREAD

**Issue by crowns741** [uyjulian/Translation-Aggregator#6]
Systran is not working anymore after site updated.

Thanks ^^

**Comment by uyjulian** [comment]
They no longer provide free online translation.

**Comment by crowns741** [comment]
You sure ? I'm using the website to translate entire chapters.

**Comment by uyjulian** [comment]
Ah, my mistake. I was looking at the wrong information.

**Comment by uyjulian** [comment]
This has been added, and will be in the next release.
