### ISSUE TITLE
Google translate is functioning, but returns text in a weird format

### ISSUE THREAD

**Issue by nagicle** [uyjulian/Translation-Aggregator#8]
Google translate is functioning, but returns text in a weird format (screen cap attached).
![error-g-1](https://user-images.githubusercontent.com/49764357/61057725-0fa6a900-a420-11e9-8824-3e5060dac59f.JPG)

**Original text:** 月曜日、まだまだ集中しなければいけなかった。

**Google translated (copied from TA):** 
Unrecognized response received:
[[["On Monday, I still had to concentrate.","月曜日、まだまだ集中しなければいけなかった。",null,null,3,null,null,null,[[["7b78faa1329566192a016d05fd7850f4","ja_en_2018q4.md"]
]
]
]
,[null,null,null,"Getsuyōbi, madamada shūchū shinakereba ikenakatta."]
]
,null,"ja",null,null,null,null,null,[["ja"]
,null,[1.0]
,["ja"]
]
]

**Comment by uyjulian** [comment]
It may be possible that the format of Google Translate has changed. I'll take a look at it later.

**Comment by henkieaardpeer** [comment]
Same problem here.

**Comment by uyjulian** [comment]
I am aware of the problem, and the fix is in my queue of things to do.

**Comment by uyjulian** [comment]
v1.0.2 is now available: https://github.com/uyjulian/Translation-Aggregator/releases/tag/v1.0.2
